version: "3"
services:
  web:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: "${IMAGE:-docker-frontend.artifacts.dbccloud.dk/bibliotekdk-next-frontend:latest}"
    environment:
      - DISABLE_DRUPAL_TRANSLATE=1
      - ENABLE_STORYBOOK=1
      - STORYBOOK_PORT=4000
      - PORT=3000
      - NEXT_BACKEND_API_URL=http://bibdk-backend-www-master.febib-prod.svc.cloud.dbc.dk
      - NEXTAUTH_SECRET=some-jwt-secret
      - ELBA_DRY_RUN=true
      - NEXTAUTH_URL=http://localhost:3000
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CYPRESS=true
      - NEXT_PUBLIC_FBI_API_URL=${NEXT_PUBLIC_FBI_API_URL}
      - NEXT_PUBLIC_FBI_API_SIMPLESEARCH_URL=${NEXT_PUBLIC_FBI_API_SIMPLESEARCH_URL}
    command: npm run start
    shm_size: "2gb"
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    shm_size: "2gb"
    image: docker-dbc.artifacts.dbccloud.dk/cypress:latest
    volumes:
      - "./:/app"
      - "/app/node_modules"

    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:4000
      - CYPRESS_nextjsBaseUrl=http://web:3000
      - CONFIG_FILE=cypress.config.js
      - CYPRESS_FOLDER=/app/cypress

    command: bash -c "npm i cypress-plugin-tab && npm run cy"
