version: '3'
services:
  web:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: '${IMAGE:-docker-ux.dbc.dk/bibliotekdk-next-frontend:latest}'
    environment:
      - DISABLE_DRUPAL_TRANSLATE=1
      - ENABLE_STORYBOOK=1
      - STORYBOOK_PORT=4000
      - PORT=3000
      - NEXT_BACKEND_API_URL=http://bibdk-backend-www-master.frontend-prod.svc.cloud.dbc.dk
      - JWT_SECRET=some-jwt-secret
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    command: npm run start
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker.dbc.dk/cypress:latest
    volumes:
      - './e2e:/app/e2e'
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:4000
      - CYPRESS_nextjsBaseUrl=http://web:3000
    command: bash -c "npm i cypress-plugin-tab && npm run cy"
