import { StoryTitle, StoryDescription } from "@/storybook";
import { Sections, SectionsSkeleton } from "./Sections";

const exportedObject = {
  title: "help/sections",
};

export default exportedObject;

/**
 * Help Sections
 * @returns {React.ReactElement | null}
 */
export function Default() {
  const data = [
    {
      nid: 1,
      title: "Some text 1",
      fieldHelpTextGroup: "Group 1",
    },
    {
      nid: 2,
      title: "Some text 2",
      fieldHelpTextGroup: "Group 1",
    },
    {
      nid: 3,
      title: "Some text 3",
      fieldHelpTextGroup: "Group 2",
    },
    {
      nid: 4,
      title: "Some text 4",
      fieldHelpTextGroup: "Group 3",
    },
    {
      nid: 5,
      title: "Some text 5",
      fieldHelpTextGroup: "Group 3",
    },
  ];

  return (
    <div>
      <StoryTitle>Help sections</StoryTitle>
      <StoryDescription>
        Help sections is autogenerated based on the available articles written
        by the bibdk team
      </StoryDescription>
      <Sections data={data} />
    </div>
  );
}

/**
 * Sections loading
 * @returns {React.ReactElement | null}
 */
export function Loading() {
  return (
    <div>
      <StoryTitle>Help sections</StoryTitle>
      <StoryDescription>Loading version of the help sections</StoryDescription>
      <SectionsSkeleton />
    </div>
  );
}
