function buildRecentSearchHistoryItems(count) {
  const now = Date.now();
  return Array.from({ length: count }).map((_, i) => {
    const q = { all: `test-${i + 1}` };
    const filters = {};
    const mode = "simpel";
    const unixtimestamp = now - i * 60 * 1000; // 1 min apart
    return {
      mode,
      q,
      filters,
      key: JSON.stringify({ mode, q, filters }),
      unixtimestamp,
      timestamp: "00.00", // kept for parity with stored shape; UI prefers unixtimestamp
    };
  });
}

function testLabel(n) {
  return new RegExp(`\\btest-${n}\\b`);
}

function visitRecentSearchesWithHistoryCount(count) {
  const nextjsBaseUrl = Cypress.env("nextjsBaseUrl");
  const items = buildRecentSearchHistoryItems(count || 0);
  cy.visit(`${nextjsBaseUrl}/find/historik/seneste`, {
    onBeforeLoad(win) {
      win.sessionStorage.setItem(
        "advanced-search-history",
        JSON.stringify(items)
      );
    },
  });
}

describe("Recent searches", () => {
  it("shows empty state when no searches have been made", () => {
    visitRecentSearchesWithHistoryCount(0);
    cy.consentAllowAll();
    cy.location("pathname").should("include", "/find/historik/seneste");

    // Empty state text
    cy.contains(
      "Her vil du kunne se en liste over de seneste søgninger, hvor der har været brugt avanceret søgning. Listen er midlertidig og nulstilles automatisk, når du lukker enten vinduet eller din browser."
    ).should("be.visible");

    // Actions should be disabled
    // Select-all is rendered as visible label text inside <label> (Checkbox does not set aria-label on input)
    cy.contains("label", /vælg alle/i)
      .find('input[type="checkbox"]')
      .should("be.disabled");
    // NOTE: "Fjern valgte" button contains both text + an Icon, which makes the
    // autogenerated data-cy unstable (Button generates data-cy from children).
    cy.contains("button", "Fjern valgte").should("be.disabled");
    cy.contains("button", "Kombiner søgninger").should("be.disabled");
  });

  it("paginates correctly for 93 items (10 pages)", () => {
    visitRecentSearchesWithHistoryCount(93);

    cy.consentAllowAll();
    cy.location("pathname").should("include", "/find/historik/seneste");

    // First page should contain test-1..test-10, but not test-11
    for (let i = 1; i <= 10; i++) {
      cy.contains(testLabel(i)).should("be.visible");
    }
    cy.contains(testLabel(11)).should("not.exist");

    // Navigate to last page (10). Page buttons are plain buttons with number text.
    cy.contains("button", "9").click();

    // Now we should see page 10 as an option (2..10 visible when currentPage=9)
    cy.contains("button", "10").should("exist").click();
    cy.contains("button", "11").should("not.exist");

    // Last page should contain remaining 3 items (93 - 9*10 = 3)
    cy.contains(testLabel(91)).should("be.visible");
    cy.contains(testLabel(92)).should("be.visible");
    cy.contains(testLabel(93)).should("be.visible");
    cy.contains(testLabel(90)).should("not.exist");
  });

  it("can delete a selected recent search", () => {
    visitRecentSearchesWithHistoryCount(3);

    cy.consentAllowAll();
    cy.location("pathname").should("include", "/find/historik/seneste");

    cy.contains(testLabel(1)).should("be.visible");
    cy.contains(testLabel(2)).should("be.visible");
    cy.contains(testLabel(3)).should("be.visible");

    // Select first item checkbox (checkboxes use aria-label="select-item-{index}")
    cy.contains("label", "select-item-0")
      .find('input[type="checkbox"]')
      .click({ force: true });

    // Delete selected
    cy.contains("button", "Fjern valgte").should("not.be.disabled").click();

    // List updates
    cy.contains(testLabel(1)).should("not.exist");
    cy.contains(testLabel(2)).should("be.visible");
    cy.contains(testLabel(3)).should("be.visible");
    cy.contains("button", "Fjern valgte").should("be.disabled");
  });

  it("delete selected only affects the current page (desktop)", () => {
    // 25 items => page 1 has test-1..test-10, page 2 has test-11..test-20, page 3 has test-21..test-25
    visitRecentSearchesWithHistoryCount(25);

    cy.consentAllowAll();
    cy.location("pathname").should("include", "/find/historik/seneste");

    // Go to page 2 and delete that page.
    // After deletion, we should stay on page 2 and see the remaining "last" items (test-21..test-25).
    cy.contains("button", /^2$/).click();
    cy.contains(testLabel(11)).should("be.visible");
    cy.contains(testLabel(1)).should("not.exist");

    // Select all on current page and delete
    cy.contains("label", /vælg alle/i)
      .find('input[type="checkbox"]')
      .click({ force: true });
    cy.contains("button", "Fjern valgte").should("not.be.disabled").click();

    // Page 2 should now show what used to be page 3 (last items)
    cy.contains(testLabel(21)).should("be.visible");
    cy.contains(testLabel(25)).should("be.visible");
    cy.contains(testLabel(11)).should("not.exist");
    cy.contains(testLabel(1)).should("not.exist");

    // No longer enough items for page 3
    cy.contains("button", /^3$/).should("not.exist");
  });

  it("mobile shows 'Se flere' when more than 10 items exist", () => {
    cy.viewport(375, 667); // iPhone-ish
    visitRecentSearchesWithHistoryCount(11);

    cy.consentAllowAll();
    cy.location("pathname").should("include", "/find/historik/seneste");

    // First page items should be visible, but not the 11th yet
    cy.contains(testLabel(1)).should("be.visible");
    cy.contains(testLabel(10)).should("be.visible");
    cy.contains(testLabel(11)).should("not.exist");

    cy.contains("button", "Se flere").should("be.visible");
  });

  it("mobile 'Se flere' loads additional items and disappears when complete", () => {
    cy.viewport(375, 667); // iPhone-ish
    visitRecentSearchesWithHistoryCount(15);

    cy.consentAllowAll();
    cy.location("pathname").should("include", "/find/historik/seneste");

    // Initially only first 10
    cy.contains(testLabel(10)).should("be.visible");
    cy.contains(testLabel(11)).should("not.exist");

    // Load more => should show remaining items
    cy.contains("button", "Se flere").click();
    cy.contains(testLabel(11)).should("be.visible");
    cy.contains(testLabel(15)).should("be.visible");

    // All items loaded => no more button
    cy.contains("button", "Se flere").should("not.exist");
  });

  it("mobile can delete selected via menu", () => {
    cy.viewport(375, 667); // iPhone-ish
    visitRecentSearchesWithHistoryCount(3);

    cy.consentAllowAll();
    cy.location("pathname").should("include", "/find/historik/seneste");

    cy.contains(testLabel(1)).should("be.visible");
    cy.contains(testLabel(2)).should("be.visible");
    cy.contains(testLabel(3)).should("be.visible");

    // Select first item checkbox (label text is "select-item-0")
    cy.contains("label", "select-item-0")
      .find('input[type="checkbox"]')
      .click({ force: true });

    // Open menu and click "Fjern valgte"
    cy.contains("button", "Administrer").click();
    cy.contains("div[role='menuitem']", "Fjern valgte").click();

    // Item should be removed
    cy.contains(testLabel(1)).should("not.exist");
    cy.contains(testLabel(2)).should("be.visible");
    cy.contains(testLabel(3)).should("be.visible");
  });

  it("can select across pages (2 selected total)", () => {
    // 25 items => 3 desktop pages
    visitRecentSearchesWithHistoryCount(25);

    cy.consentAllowAll();
    cy.location("pathname").should("include", "/find/historik/seneste");

    // Page 1: select first row (test-1 is newest => first row)
    cy.contains(testLabel(1)).should("be.visible");
    cy.contains("label", "select-item-0")
      .find('input[type="checkbox"]')
      .click({ force: true });
    cy.contains(/^1 valgt$/).should("be.visible");

    // Page 2: select first row (test-11 is first on page 2)
    cy.contains("button", /^2$/).click();
    cy.contains(testLabel(11)).should("be.visible");
    cy.contains("label", "select-item-0")
      .find('input[type="checkbox"]')
      .click({ force: true });

    // Selection count should be global across pages
    cy.contains(/^2 valgt$/).should("be.visible");
  });
});
