/**
 * @file
 * Alias tables for controlled-vocabulary values: what a user (or the model)
 * is likely to write → the Danish controlled value used by FBI-API.
 *
 * Keys are matched after normalization (lowercase, trimmed, single spaces).
 * A value here is used as the *lookup key* against the vocabulary, so it
 * still has to exist in vocab.json to become an exact phrase match.
 */

const LANGUAGES = {
  danish: "dansk",
  english: "engelsk",
  german: "tysk",
  french: "fransk",
  spanish: "spansk",
  italian: "italiensk",
  portuguese: "portugisisk",
  swedish: "svensk",
  norwegian: "norsk",
  finnish: "finsk",
  icelandic: "islandsk",
  dutch: "nederlandsk (hollandsk)",
  nederlandsk: "nederlandsk (hollandsk)",
  hollandsk: "nederlandsk (hollandsk)",
  polish: "polsk",
  russian: "russisk",
  ukrainian: "ukrainsk",
  arabic: "arabisk",
  turkish: "tyrkisk",
  persian: "persisk",
  farsi: "persisk",
  chinese: "kinesisk",
  japanese: "japansk",
  korean: "koreansk",
  greek: "græsk",
  hindi: "hindi",
  urdu: "urdu",
  somali: "somali",
  vietnamese: "vietnamesisk",
  thai: "thai",
  greenlandic: "kalaallisut",
  grønlandsk: "kalaallisut",
  faroese: "færøsk",
  latin: "latin",
  // adjective/noun forms in Danish
  engelsksproget: "engelsk",
  dansksproget: "dansk",
  tysksproget: "tysk",
  fransksproget: "fransk",
};

const GENRES = {
  "sci-fi": "science fiction",
  scifi: "science fiction",
  "science-fiction": "science fiction",
  roman: "romaner",
  novel: "romaner",
  novels: "romaner",
  krimier: "krimi",
  kriminalroman: "krimi",
  kriminalromaner: "krimi",
  crime: "krimi",
  "crime fiction": "krimi",
  thrillers: "thriller",
  novelle: "noveller",
  "short stories": "noveller",
  digt: "digte",
  poesi: "digte",
  poetry: "digte",
  lyrik: "digte",
  biografi: "biografier",
  biography: "biografier",
  biographies: "biografier",
  tegneserie: "tegneserier",
  comics: "tegneserier",
  comic: "tegneserier",
  "graphic novel": "graphic novels",
  horror: "gys",
  gyser: "gys",
  gysere: "gys",
  eventyr: "eventyr",
  "fairy tales": "eventyr",
  fantasy: "fantasy",
  humor: "humor",
  humour: "humor",
  comedy: "humor",
  komedie: "humor",
  dokumentar: "dokumentarfilm",
  documentary: "dokumentarfilm",
  documentaries: "dokumentarfilm",
  erindring: "erindringer",
  memoir: "erindringer",
  memoirs: "erindringer",
  "historisk roman": "historiske romaner",
  "historical fiction": "historiske romaner",
  kærlighedsroman: "kærlighedsromaner",
  romance: "kærlighedsromaner",
  "romantic fiction": "kærlighedsromaner",
  spændingsroman: "spænding",
  spændingsromaner: "spænding",
  suspense: "spænding",
  ungdomsroman: "ungdomsbøger",
  ungdomsromaner: "ungdomsbøger",
  "young adult": "ungdomsbøger",
  ya: "ungdomsbøger",
  børnebog: "børnebøger",
  billedbog: "billedbøger",
  "picture book": "billedbøger",
  kogebog: "kogebøger",
  cookbook: "kogebøger",
  cookbooks: "kogebøger",
};

const SPECIFIC_MATERIAL_TYPES = {
  bøger: "bog",
  book: "bog",
  books: "bog",
  paperback: "bog",
  hardback: "bog",
  lydbøger: "lydbog",
  audiobook: "lydbog",
  audiobooks: "lydbog",
  "audio book": "lydbog",
  ebog: "e-bog",
  ebook: "e-bog",
  ebooks: "e-bog",
  "e-bøger": "e-bog",
  "e-book": "e-bog",
  "e-books": "e-bog",
  billedbøger: "billedbog",
  "picture book": "billedbog",
  tegneserier: "tegneserie",
  comic: "tegneserie",
  comics: "tegneserie",
  artikler: "artikel",
  article: "artikel",
  articles: "artikel",
  dvd: "film (dvd)",
  "blu-ray": "film (blu-ray)",
  bluray: "film (blu-ray)",
  cd: "musik (cd)",
  vinyl: "musik (grammofonplade)",
  lp: "musik (grammofonplade)",
  noder: "node",
  "sheet music": "node",
};

const GENERAL_MATERIAL_TYPES = {
  bog: "bøger",
  book: "bøger",
  books: "bøger",
  lydbog: "lydbøger",
  audiobook: "lydbøger",
  audiobooks: "lydbøger",
  ebog: "e-bøger",
  "e-bog": "e-bøger",
  ebook: "e-bøger",
  ebooks: "e-bøger",
  movie: "film",
  movies: "film",
  music: "musik",
  spil: "computerspil",
  game: "computerspil",
  games: "computerspil",
  "video games": "computerspil",
  artikel: "artikler",
  article: "artikler",
  articles: "artikler",
  tegneserie: "tegneserier",
  comics: "tegneserier",
  "sheet music": "noder",
  tidsskrift: "aviser og tidsskrifter",
  tidsskrifter: "aviser og tidsskrifter",
  magazine: "aviser og tidsskrifter",
  magazines: "aviser og tidsskrifter",
  avis: "aviser og tidsskrifter",
  aviser: "aviser og tidsskrifter",
  newspaper: "aviser og tidsskrifter",
  newspapers: "aviser og tidsskrifter",
  "board game": "brætspil",
  "board games": "brætspil",
  podcast: "podcasts",
};

const GAME_PLATFORMS = {
  ps4: "playstation 4",
  ps5: "playstation 5",
  ps3: "playstation 3",
  playstation: "playstation",
  xbox: "xbox",
  "xbox series": "xbox series x",
  "xbox series x/s": "xbox series x",
  switch: "nintendo switch",
  nintendo: "nintendo",
  pc: "computerspil*",
  computer: "computerspil*",
  windows: "computerspil*",
  "pc-spil": "computerspil*",
};

const FILM_NATIONALITIES = {
  fransk: "franske film",
  french: "franske film",
  frankrig: "franske film",
  france: "franske film",
  dansk: "danske film",
  danish: "danske film",
  danmark: "danske film",
  denmark: "danske film",
  svensk: "svenske film",
  swedish: "svenske film",
  sverige: "svenske film",
  norsk: "norske film",
  norwegian: "norske film",
  norge: "norske film",
  tysk: "tyske film",
  german: "tyske film",
  tyskland: "tyske film",
  germany: "tyske film",
  italiensk: "italienske film",
  italian: "italienske film",
  italien: "italienske film",
  italy: "italienske film",
  spansk: "spanske film",
  spanish: "spanske film",
  spanien: "spanske film",
  spain: "spanske film",
  amerikansk: "amerikanske film",
  american: "amerikanske film",
  usa: "amerikanske film",
  britiske: "engelske film",
  britisk: "engelske film",
  british: "engelske film",
  engelsk: "engelske film",
  england: "engelske film",
  storbritannien: "engelske film",
  uk: "engelske film",
  japansk: "japanske film",
  japanese: "japanske film",
  japan: "japanske film",
  koreansk: "koreanske film",
  korean: "koreanske film",
  korea: "koreanske film",
  kinesisk: "kinesiske film",
  chinese: "kinesiske film",
  kina: "kinesiske film",
  china: "kinesiske film",
  indisk: "indiske film",
  indian: "indiske film",
  indien: "indiske film",
  india: "indiske film",
  bollywood: "indiske film",
  iransk: "iranske film",
  iranian: "iranske film",
  iran: "iranske film",
  finsk: "finske film",
  finnish: "finske film",
  finland: "finske film",
  islandsk: "islandske film",
  icelandic: "islandske film",
  island: "islandske film",
  iceland: "islandske film",
  russisk: "russiske film",
  russian: "russiske film",
  polsk: "polske film",
  polish: "polske film",
  tyrkisk: "tyrkiske film",
  turkish: "tyrkiske film",
  australsk: "australske film",
  australian: "australske film",
  canadisk: "canadiske film",
  canadian: "canadiske film",
  mexicansk: "mexicanske film",
  mexican: "mexicanske film",
  brasiliansk: "brasilianske film",
  brazilian: "brasilianske film",
  hollandske: "nederlandske film",
  hollandsk: "nederlandske film",
  nederlandsk: "nederlandske film",
  dutch: "nederlandske film",
  holland: "nederlandske film",
  belgisk: "belgiske film",
  belgian: "belgiske film",
  irsk: "irske film",
  irish: "irske film",
  græsk: "græske film",
  greek: "græske film",
  argentinsk: "argentinske film",
  argentinian: "argentinske film",
};

const GENERAL_AUDIENCE = {
  letlæst: "let at læse",
  letlæste: "let at læse",
  letlæsning: "let at læse",
  "easy to read": "let at læse",
  "easy reader": "let at læse",
  ordblinde: "let at læse",
  dyslexia: "let at læse",
  dyslexic: "let at læse",
  læsesvage: "let at læse",
  højtlæsning: "for højtlæsning",
  "read aloud": "for højtlæsning",
  begynderlæsere: "for begynderlæsere",
};

const PRIMARY_TARGET = {
  folkeskole: "folkeskoleniveau",
  folkeskolen: "folkeskoleniveau",
  grundskole: "folkeskoleniveau",
  gymnasie: "gymnasieniveau",
  gymnasiet: "gymnasieniveau",
  gymnasium: "gymnasieniveau",
  "high school": "gymnasieniveau",
  førskole: "førskoleniveau",
  børnehave: "førskoleniveau",
  preschool: "førskoleniveau",
  universitet: "forskningsniveau",
  forskning: "forskningsniveau",
  university: "forskningsniveau",
};

/**
 * Alias tables keyed by vocabulary name (see FIELDS[field].vocab).
 */
export const ALIASES = Object.freeze({
  mainlanguage: LANGUAGES,
  spokenlanguage: LANGUAGES,
  subtitlelanguage: LANGUAGES,
  language: LANGUAGES,
  genreandform: GENRES,
  specificmaterialtype: SPECIFIC_MATERIAL_TYPES,
  generalmaterialtype: GENERAL_MATERIAL_TYPES,
  gameplatform: GAME_PLATFORMS,
  filmnationality: FILM_NATIONALITIES,
  generalaudience: GENERAL_AUDIENCE,
  primarytarget: PRIMARY_TARGET,
});
